### ISSUE TITLE
Implement overwrite

### ISSUE THREAD

**Issue by M3ssman** [OCR-D/core#521] opened 2020-06-17 07:57 UTC
# Problem
If a make-Target is translated into bash-call it fails for i.e. `OCR-D-IMG-PNG`

```
make[1]: Entering directory '/data/1000'
building OCR-D-IMG-PNG from MAX with pattern rule for ocrd-im6convert
STAMP=`test -e OCR-D-IMG-PNG && date -Ins -r OCR-D-IMG-PNG`; ocrd-im6convert   -I MAX -p OCR-D-IMG-PNG.json -O OCR-D-IMG-PNG --overwrite 2>&1 | tee OCR-D-IMG-PNG.log && touch -c OCR-D-IMG-PNG || { if test -z "$STAMP"; then rm -fr OCR-D-IMG-PNG; else touch -c -d "$STAMP" OCR-D-IMG-PNG; fi; false; }
ERROR: Unknown option '--overwrite'
Makefile:313: recipe for target 'OCR-D-IMG-PNG' failed
make[1]: *** [OCR-D-IMG-PNG] Error 1
make[1]: Leaving directory '/data/1000'
```

# Solution
Please implement `--overwrite` in bashlib part of core

**Comment by bertsky** [comment] 2020-06-17 08:38
duplicate of #476

**Closed** 2020-06-17 09:55 UTC
