### ISSUE TITLE
ocrd workspace bulk-add --help: code formatting broken

### ISSUE THREAD

**Issue by kba** [OCR-D/core#769] opened 2021-12-20 12:08 UTC
```
  \b Example:     ocrd workspace bulk-add \\             --regex
  '^.*/(?P<fileGrp>[^/]+)/page_(?P<pageid>.*)\.(?P<ext>[^\.]*)$' \\
  --file-id 'FILE_{{ fileGrp }}_{{ pageid }}' \\             --page-id
  'PHYS_{{ pageid }}' \\             --file-grp "{{ fileGrp }}" \\
  --url '{{ fileGrp }}/FILE_{{ pageid }}.{{ ext }}' \\
  path/to/files/*/*.*
```

is hard to read

**Comment by bertsky** [comment] 2021-12-20 12:30
duplicate of #641 

(I wonder why our `\b` does not work here BTW...)

**Comment by kba** [comment] 2021-12-21 10:23
Because the docstring has a `r` prefix, fixed in 3bfcc7ee as part of fixing #754

**Closed** 2022-02-01 18:25 UTC
