### ISSUE TITLE
Using a non-existant file group as input to a processor should be fatal

### ISSUE THREAD

**Issue by kba** [OCR-D/core#253] opened 2019-06-25 13:34 UTC
c.f. https://github.com/OCR-D/ocrd_tesserocr/issues/47#issuecomment-504059556

**Comment by mikegerber** [comment] 2019-06-25 14:44
Isn't this a dupe of #251?

**Comment by wrznr** [comment] 2019-07-18 09:18
Closed as duplicate (#251).

**Closed by wrznr** 2019-07-18 09:18 UTC
